services:
  db:
    image: mysql:8.0
    container_name: playforyouapp-db
    restart: always
    environment:
      MYSQL_DATABASE: playforyou_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5000:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: playforyou-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/playforyou_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: playforyou-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge